server:
  port: 8083
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

ly:
  oss:
    accessKeyId: LTAI4FgyGHCpgMhdD2LPV2J8 #你自己的accessKeyId
    accessKeySecret: TbSwvMOoyDh9LJ0CLwhrQG96ArYFRj #你自己的accessKeySecret
    host: http://image.leyou.com #mant.oss-cn-beijing.aliyuncs.com #访问oss的域名，很重要bucket + endpoint
    endpoint: oss-cn-beijing.aliyuncs.com # 你的服务的端点，不一定跟我一样
    dir: "" # 保存到bucket的某个子目录
    expireTime: 20 # 过期时间，单位是S
    maxFileSize: 5242880 #文件大小限制，这里是5M