server:
  port: 8083
#服务名称
spring:
  application:
    name: search-service
#配置elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
#是否在注册中心显示ip
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#配置负载均衡
ribbon:
  ConnectTimeout: 500 # 连接超时时长
  ReadTimeout: 2000 # 数据通信超时时长
  MaxAutoRetries: 0 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 1 # 重试多少次服务
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试 GET PUT DELETE POST

rocketmq:
  name-server: 127.0.0.1:9876