server:
  port: 10010
spring:
  application:
    name: ly-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon:
  ConnectTimeout: 500 # ribbon链接超时时长
  ReadTimeout: 2000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    upload-service: /upload/** # 将上传图片微服务映射到/upload/**
    search-service: /search/** # 搜索微服务映射到/search/**
    user-service: /user/** # 用户中心微服务映射到/user/**
    auth-service: /auth/** # 授权中心微服务映射到/auth/**
    cart-service: /cart/** # 购物车微服务映射到/cart/**
    order-service:
      path: /order/** # 购物车微服务映射到/order/**
      serviceId: order-service
      strip-prefix: false #是否去掉前缀

  sensitive-headers: #什么都不写 就代表着什么都不敏感

ly: #配置跨域信息
  cors:
    allowedOrigins:
      - http://manage.leyou.com
      - http://www.leyou.com
      - http://127.0.0.1:9001
    allowedCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 3600
    filterPath: "/**"

  jwt:
    pubKeyPath: F:/LeyouXiangMu/id_rsa.pub # 公钥地址

    user:
     cookieName: LY_TOKEN


  filter:
    allowPaths:
      - /api/auth/login
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
      - /zuul/api/upload
