server:
  port: 12000
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hear_the_rest_of_your_life/leyou-config.git #这里要写自己的git地址

#rabbitMQ地址
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /leyou
    username: guest
    password: guest
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh